### ISSUE TITLE
tracrRNA sequences used to generate typeV covariance Models

### ISSUE THREAD

**Issue by Huanle** [BackofenLab/CRISPRtracrRNA#10]
Hi @Alexander-Mitrofanov,

Thank you and your colleagues for developing such a valuable tool for the community.
I wonder if you can generously share with me the specieifc trascrRNA sequences (together with the corresponding subtype information) used to generate the typeV covariance matrix?

Best Regards,

Huanle

**Comment by Alexander-Mitrofanov** [comment]
Hello Huanle,

I'm sorry for not getting back to you sooner. 
I will contact Marcus Ziemann and provide the source for the type V tracrRNAs shortly

**Comment by Alexander-Mitrofanov** [comment]
I have got the corresponding file from Marcus
[tracrRNAs_of_type_VK.csv](https://github.com/user-attachments/files/15552086/tracrRNAs_of_type_VK.csv)

**Comment by Huanle** [comment]
Hi @Alexander-Mitrofanov ,

Thanks heaps for your help. I trully appreciate it.

Best - Huanle
